json.id user.id
json.firstname user.firstname
json.lastname user.lastname
json.email user.email
json.gender user.gender
json.birthday user.birthday
json.hometown user.hometown
json.occupation user.occupation
json.photo_url asset_path(user.photo.url)
json.background_url asset_path(user.background.url)
